services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - ${JELLYFIN_CONFIG}:/config
      - ${JELLYFIN_CACHE}:/cache
      - ${JELLYFIN_TRANSCODE}:/transcode
      - ${TV_PATH}:/tv:ro
      - ${MOVIES_PATH}:/movies:ro
    ports:
      - 8096:8096
    networks:
      - media-server-network
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${BAZARR_CONFIG}:/config
      - ${TV_PATH}:/tv
      - ${MOVIES_PATH}:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - media-server-network

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - "8080:8080"
    volumes:
      - ${DOWNLOADS_PATH}:/downloads
      - ${QBITTORRENT_CONFIG}:/config
    networks:
      - media-server-network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${PROWLARR_CONFIG}:/config
    ports:
      - 9696:9696
    networks:
      - media-server-network
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ${RADARR_CONFIG}:/config
      - ${MOVIES_PATH}:/movies
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - 7878:7878
    networks:
      - media-server-network
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ${SONARR_CONFIG}:/config
      - ${TV_PATH}:/tv
      - ${DOWNLOADS_PATH}:/downloads
    ports:
      - 8989:8989
    networks:
      - media-server-network
    restart: unless-stopped

networks:
  media-server-network:
    driver: bridge
